// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSdvjPOC7WBZ9VKBytaCXx_wI63g0Y02Y',
    appId: '1:694330847385:web:194c789063e7ed00d98808',
    messagingSenderId: '694330847385',
    projectId: 'demoo-f57e5',
    authDomain: 'demoo-f57e5.firebaseapp.com',
    storageBucket: 'demoo-f57e5.appspot.com',
    measurementId: 'G-KCTRLMP0BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCee4sD4OTagQx0TjLShkXHfxO9M3alOQU',
    appId: '1:694330847385:android:8a7202c56a271924d98808',
    messagingSenderId: '694330847385',
    projectId: 'demoo-f57e5',
    storageBucket: 'demoo-f57e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRFSpc1VIRNqWlZaiJ9Q-Kqlgsk2VYirk',
    appId: '1:694330847385:ios:04e081b00392d998d98808',
    messagingSenderId: '694330847385',
    projectId: 'demoo-f57e5',
    storageBucket: 'demoo-f57e5.appspot.com',
    iosClientId: '694330847385-o00nomgg8vbl1q6uhddqphl1raai4sp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.theMetabolixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRFSpc1VIRNqWlZaiJ9Q-Kqlgsk2VYirk',
    appId: '1:694330847385:ios:939bcff04dab1c46d98808',
    messagingSenderId: '694330847385',
    projectId: 'demoo-f57e5',
    storageBucket: 'demoo-f57e5.appspot.com',
    iosClientId: '694330847385-e0obj8e4qu82uc703ke2g5rt0rj565rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.theMetabolixApp.RunnerTests',
  );
}
